apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 7
images:
  - name: schoolofdevops/vote
    newTag: v4
namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "sre@example.com"

configMapGenerator:
  - name: vote-options
    envs:         
      - options.env
